---
- name: install ntp
  apt: 
    name: ntp 
    state: present

- name: configure ntp file /etc/ntp.conf
  template: 
    src: ntp.conf.j2 
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart ntp

- name: start ntp
  service: 
    name: ntp
    state: started
    enabled: yes